In [9]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.datasets import make_classification, make_regression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [10]:
df = pd.read_csv("/home/chaitanya/Downloads/archive/WA_Fn-UseC_-HR-Employee-Attrition.csv")
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [11]:
DF = df.copy()

In [12]:
DF['BusinessTravel'] = DF['BusinessTravel'].replace('Travel_Rarely',2)
DF['BusinessTravel'] = DF['BusinessTravel'].replace('Travel_Frequently',3)
DF['BusinessTravel'] = DF['BusinessTravel'].replace('Non-Travel',4)

DF['Attrition'] = DF['Attrition'].replace('Yes',2)
DF['Attrition'] = DF['Attrition'].replace('No',3)

DF['OverTime'] = DF['OverTime'].replace('Yes',2)
DF['OverTime'] = DF['OverTime'].replace('No',3)

DF['Gender'] = DF['Gender'].replace('Male',2)
DF['Gender'] = DF['Gender'].replace('Female',3)

DF['MaritalStatus'] = DF['MaritalStatus'].replace('Single',2)
DF['MaritalStatus'] = DF['MaritalStatus'].replace('Married',3)
DF['MaritalStatus'] = DF['MaritalStatus'].replace('Divorced',4)

DF['Department'] = DF['Department'].replace('Sales',2)
DF['Department'] = DF['Department'].replace('Human Resources',3)
DF['Department'] = DF['Department'].replace('Research & Development',4)

DF['EducationField'] = DF['EducationField'].replace('Life Sciences',2)
DF['EducationField'] = DF['EducationField'].replace('Medical',3)
DF['EducationField'] = DF['EducationField'].replace('Marketing',4)
DF['EducationField'] = DF['EducationField'].replace('Technical Degree',2)
DF['EducationField'] = DF['EducationField'].replace('Human Resources',3)
DF['EducationField'] = DF['EducationField'].replace('Other',4)

DF['JobRole'] = DF['JobRole'].replace('Sales Executive',2)
DF['JobRole'] = DF['JobRole'].replace('Manufacturing Director',3)
DF['JobRole'] = DF['JobRole'].replace('Healthcare Representative',4)
DF['JobRole'] = DF['JobRole'].replace('Manager',2)
DF['JobRole'] = DF['JobRole'].replace('Research Director',3)
DF['JobRole'] = DF['JobRole'].replace('Laboratory Technician',4)
DF['JobRole'] = DF['JobRole'].replace('Sales Representative',2)
DF['JobRole'] = DF['JobRole'].replace('Research Scientist',3)
DF['JobRole'] = DF['JobRole'].replace('Human Resources',4)

In [13]:
DF = DF.drop(['MonthlyIncome' ,'YearsInCurrentRole' , 'YearsAtCompany', 'YearsWithCurrManager'],axis=1)

In [15]:
from sklearn.preprocessing import MinMaxScaler
# Select only the numeric columns from DF
numeric_cols = DF.select_dtypes(include=['number']).columns.tolist()

# Create a new DataFrame with only the numeric columns
DF_numeric = DF[numeric_cols]

# Initialize the MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))

# Fit and transform the scaler on the numeric columns
norm = scaler.fit_transform(DF_numeric)

# Create a DataFrame with the scaled values
norm_df = pd.DataFrame(norm, columns=DF_numeric.columns)

In [16]:
# Split the data into features (X) and the target variable (y)
X = norm_df.drop(columns=['Attrition'])
y = DF['Attrition']  # Assuming 'Attrition' is your target variable

# Split the data into training and testing sets (e.g., 70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [17]:
def create_classification_data():
    X, y = make_classification(n_samples=1000, n_features=10, random_state=42)
    return X, y

In [18]:
# Create a sample regression dataset
def create_regression_data():
    X, y = make_regression(n_samples=1000, n_features=10, noise=0.1, random_state=42)
    return X, y

In [19]:
# Define the ANN model for classification
def build_classification_model(input_dim):
    model = Sequential([
        Dense(64, activation='relu', input_dim=input_dim),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [20]:
# Define the ANN model for regression
def build_regression_model(input_dim):
    model = Sequential([
        Dense(64, activation='relu', input_dim=input_dim),
        Dense(32, activation='relu'),
        Dense(1)
    ])
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])
    return model

In [22]:
# Load and preprocess data
X_classification, y_classification = create_classification_data()
X_regression, y_regression = create_regression_data()

scaler_classification = StandardScaler()
X_classification = scaler_classification.fit_transform(X_classification)

scaler_regression = StandardScaler()
X_regression = scaler_regression.fit_transform(X_regression)

# Split data into train and test sets
X_train_classification, X_test_classification, y_train_classification, y_test_classification = train_test_split(
    X_classification, y_classification, test_size=0.2, random_state=42)

X_train_regression, X_test_regression, y_train_regression, y_test_regression = train_test_split(
    X_regression, y_regression, test_size=0.2, random_state=42)

# Build and train the classification model
classification_model = build_classification_model(X_classification.shape[1])
classification_model.fit(X_train_classification, y_train_classification, epochs=10, batch_size=32, validation_data=(X_test_classification, y_test_classification))

# Build and train the regression model
regression_model = build_regression_model(X_regression.shape[1])
regression_model.fit(X_train_regression, y_train_regression, epochs=20, batch_size=32, validation_data=(X_test_regression, y_test_regression))

Epoch 1/10
25/25 [==============================] - 1s 8ms/step - loss: 0.6112 - accuracy: 0.6950 - val_loss: 0.5232 - val_accuracy: 0.8250
Epoch 2/10
25/25 [==============================] - 0s 5ms/step - loss: 0.4460 - accuracy: 0.8438 - val_loss: 0.4262 - val_accuracy: 0.8350
Epoch 3/10
25/25 [==============================] - 0s 5ms/step - loss: 0.3643 - accuracy: 0.8612 - val_loss: 0.3848 - val_accuracy: 0.8400
Epoch 4/10
25/25 [==============================] - 0s 5ms/step - loss: 0.3269 - accuracy: 0.8725 - val_loss: 0.3736 - val_accuracy: 0.8450
Epoch 5/10
25/25 [==============================] - 0s 4ms/step - loss: 0.3114 - accuracy: 0.8700 - val_loss: 0.3727 - val_accuracy: 0.8450
Epoch 6/10
25/25 [==============================] - 0s 5ms/step - loss: 0.3026 - accuracy: 0.8700 - val_loss: 0.3704 - val_accuracy: 0.8450
Epoch 7/10
25/25 [==============================] - 0s 5ms/step - loss: 0.2978 - accuracy: 0.8737 - val_loss: 0.3647 - val_accuracy: 0.8350
Epoch 8/10
25/25 [==============================] - 0s 4ms/step - loss: 0.2930 - accuracy: 0.8750 - val_loss: 0.3680 - val_accuracy: 0.8450
Epoch 9/10
25/25 [==============================] - 0s 4ms/step - loss: 0.2900 - accuracy: 0.8725 - val_loss: 0.3658 - val_accuracy: 0.8350
Epoch 10/10
25/25 [==============================] - 0s 5ms/step - loss: 0.2846 - accuracy: 0.8750 - val_loss: 0.3642 - val_accuracy: 0.8350
Epoch 1/20
25/25 [==============================] - 1s 12ms/step - loss: 17525.9004 - mae: 104.9400 - val_loss: 17042.0391 - val_mae: 104.7283
Epoch 2/20
25/25 [==============================] - 0s 5ms/step - loss: 17350.6543 - mae: 104.4066 - val_loss: 16815.1621 - val_mae: 104.0161
Epoch 3/20
25/25 [==============================] - 0s 5ms/step - loss: 17022.8652 - mae: 103.3755 - val_loss: 16370.4336 - val_mae: 102.5849
Epoch 4/20
25/25 [==============================] - 0s 5ms/step - loss: 16385.5957 - mae: 101.3154 - val_loss: 15557.6426 - val_mae: 99.8810
Epoch 5/20
25/25 [==============================] - 0s 4ms/step - loss: 15269.4541 - mae: 97.5358 - val_loss: 14206.1602 - val_mae: 95.1922
Epoch 6/20
25/25 [==============================] - 0s 4ms/step - loss: 13533.0264 - mae: 91.4663 - val_loss: 12296.9473 - val_mae: 88.1035
Epoch 7/20
25/25 [==============================] - 0s 5ms/step - loss: 11203.6162 - mae: 82.5954 - val_loss: 9842.3672 - val_mae: 78.0666
Epoch 8/20
25/25 [==============================] - 0s 5ms/step - loss: 8464.7285 - mae: 70.5872 - val_loss: 7123.8276 - val_mae: 65.1490
Epoch 9/20
25/25 [==============================] - 0s 5ms/step - loss: 5730.1426 - mae: 56.5634 - val_loss: 4530.7227 - val_mae: 50.5342
Epoch 10/20
25/25 [==============================] - 0s 3ms/step - loss: 3371.9229 - mae: 41.9639 - val_loss: 2563.7131 - val_mae: 36.3244
Epoch 11/20
25/25 [==============================] - 0s 4ms/step - loss: 1783.9950 - mae: 29.4550 - val_loss: 1332.4437 - val_mae: 25.5587
Epoch 12/20
25/25 [==============================] - 0s 4ms/step - loss: 916.6207 - mae: 20.9269 - val_loss: 709.3245 - val_mae: 19.0483
Epoch 13/20
25/25 [==============================] - 0s 5ms/step - loss: 522.8324 - mae: 16.2845 - val_loss: 439.9498 - val_mae: 15.3720
Epoch 14/20
25/25 [==============================] - 0s 5ms/step - loss: 354.7241 - mae: 13.7508 - val_loss: 312.5181 - val_mae: 13.0530
Epoch 15/20
25/25 [==============================] - 0s 5ms/step - loss: 269.6622 - mae: 12.1057 - val_loss: 234.7020 - val_mae: 11.3161
Epoch 16/20
25/25 [==============================] - 0s 5ms/step - loss: 216.0269 - mae: 10.8856 - val_loss: 188.9440 - val_mae: 10.2010
Epoch 17/20
25/25 [==============================] - 0s 5ms/step - loss: 183.7356 - mae: 10.1635 - val_loss: 160.8481 - val_mae: 9.6307
Epoch 18/20
25/25 [==============================] - 0s 4ms/step - loss: 160.8398 - mae: 9.7955 - val_loss: 143.0141 - val_mae: 9.1525
Epoch 19/20
25/25 [==============================] - 0s 4ms/step - loss: 144.7868 - mae: 9.2717 - val_loss: 129.3863 - val_mae: 8.7118
Epoch 20/20
25/25 [==============================] - 0s 4ms/step - loss: 133.5399 - mae: 8.8319 - val_loss: 123.2342 - val_mae: 8.6007